---
- name: Install httpd package
  yum: 
    name: httpd
    state: present

- name: start httpd
  service:
    name: httpd
    state: started

- name: Opn port for http
  firewalld:
    service: http
    permanent: true
    state: enabled 


- name: Restart firewalld
  service:
    name: firewalld
    state: reloaded
